kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-storage-claim
  labels:
    app: mongo-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
